### ISSUE TITLE
Update code structure

### ISSUE THREAD

**Issue by paaanic** [vk-cs/terraform-provider-vkcs#162]
`vkcs`:
- ...
- `blockstorage`:
  - `blockstorage_snapshot.go`
  - `blockstorage_volume.go`
  - `data_source_blockstorage_snapshot.go`
  - `data_source_blockstorage_snapshot_test.go`
  - `data_source_blockstorage_volume.go`
  - `data_source_blockstorage_volume_test.go`
  - `resource_blockstorage_volume.go`
  - `resource_blockstorage_volume_snapshot.go`
  - `resource_blockstorage_volume_snapshot_test.go`
  - `resource_blockstorage_volume_test.go`
- `compute`:
  - `compute_floatingip_associate.go`
  - `compute_instance.go`
  - `compute_interface_attach.go`
  - `compute_interface_attach_test.go`
  - `compute_keypair.go`
  - `compute_keypair_test.go`
  - `compute_servergroup.go`
  - `compute_servergroup_test.go`
  - `compute_volume_attach.go`
  - `compute_volume_attach_test.go`
  - `data_source_compute_availability_zones.go`
  - `data_source_compute_availability_zones_test.go`
  - `data_source_compute_flavor.go`
  - `data_source_compute_flavor_test.go`
  - `data_source_compute_instance.go`
  - `data_source_compute_instance_test.go`
  - `data_source_compute_keypair.go`
  - `data_source_compute_keypair_test.go`
  - `data_source_compute_quotaset.go`
  - `data_source_compute_quotaset_test.go`
  - `resource_compute_floatingip_associate.go`
  - `resource_compute_floatingip_associate_test.go`
  - `resource_compute_instance.go`
  - `resource_compute_instance_test.go`
  - `resource_compute_interface_attach.go`
  - `resource_compute_interface_attach_test.go`
  - `resource_compute_keypair.go`
  - `resource_compute_keypair_test.go`
  - `resource_compute_servergroup.go`
  - `resource_compute_servergroup_test.go`
  - `resource_compute_volume_attach.go`
  - `resource_compute_volume_attach_test.go`
- `db`:
  - `data_source_db_backup.go`
  - `data_source_db_backup_test.go`
  - `data_source_db_config_group.go`
  - `data_source_db_config_group_test.go`
  - `data_source_db_database.go`
  - `data_source_db_database_test.go`
  - `data_source_db_datastore.go`
  - `data_source_db_datastore_capabilities.go`
  - `data_source_db_datastore_capabilities_test.go`
  - `data_source_db_datastore_parameters.go`
  - `data_source_db_datastore_parameters_test.go`
  - `data_source_db_datastore_test.go`
  - `data_source_db_datastores.go`
  - `data_source_db_datastores_test.go`
  - `data_source_db_instance.go`
  - `data_source_db_instance_test.go`
  - `data_source_db_user.go`
  - `data_source_db_user_test.go`
  - `db_backup.go`
  - `db_cluster.go`
  - `db_config_group.go`
  - `db_database.go`
  - `db_instance.go`
  - `db_instance_test.go`
  - `db_shared.go`
  - `db_user.go`
  - `db_user_test.go`
  - `resource_db_backup.go`
  - `resource_db_backup_test.go`
  - `resource_db_cluster.go`
  - `resource_db_cluster_test.go`
  - `resource_db_cluster_with_shards.go`
  - `resource_db_cluster_with_shards_test.go`
  - `resource_db_config_group.go`
  - `resource_db_config_group_test.go`
  - `resource_db_database.go`
  - `resource_db_database_test.go`
  - `resource_db_instance.go`
  - `resource_db_instance_test.go`
  - `resource_db_user.go`
  - `resource_db_user_test.go`
- `images`:
  - `data_source_images_image.go`
  - `data_source_images_image_test.go`
  - `images_image.go`
  - `resource_images_image.go`
  - `resource_images_image_test.go`
- `keymanager`:
  - `data_source_keymanager_container.go`
  - `data_source_keymanager_container_test.go`
  - `data_source_keymanager_secret.go`
  - `data_source_keymanager_secret_test.go`
  - `keymanager.go`
  - `keymanager_container.go`
  - `keymanager_secret.go`
  - `resource_keymanager_container.go`
  - `resource_keymanager_container_test.go`
  - `resource_keymanager_secret.go`
  - `resource_keymanager_secret_test.go`
- `kubernetes`:
  - `data_source_kubernetes_cluster.go`
  - `data_source_kubernetes_cluster_template.go`
  - `data_source_kubernetes_cluster_template_test.go`
  - `data_source_kubernetes_cluster_templates.go`
  - `data_source_kubernetes_cluster_templates_test.go`
  - `data_source_kubernetes_cluster_test.go`
  - `data_source_kubernetes_node_group.go`
  - `data_source_kubernetes_node_group_test.go`
  - `kubernetes_shared.go`
  - `kubernetes_shared_test.go`
  - `resource_kubernetes_cluster.go`
  - `resource_kubernetes_cluster_test.go`
  - `resource_kubernetes_node_group.go`
  - `resource_kubernetes_node_group_test.go`
- `lb`:
  - `data_source_lb_loadbalancer.go`
  - `data_source_lb_loadbalancer_test.go`
  - `lb_shared.go`
  - `lb_shared_test.go`
  - `resource_lb_l7policy.go`
  - `resource_lb_l7policy_test.go`
  - `resource_lb_l7rule.go`
  - `resource_lb_l7rule_test.go`
  - `resource_lb_listener.go`
  - `resource_lb_listener_test.go`
  - `resource_lb_loadbalancer.go`
  - `resource_lb_loadbalancer_test.go`
  - `resource_lb_member.go`
  - `resource_lb_member_test.go`
  - `resource_lb_members.go`
  - `resource_lb_members_test.go`
  - `resource_lb_monitor.go`
  - `resource_lb_monitor_test.go`
  - `resource_lb_pool.go`
  - `resource_lb_pool_test.go`
- `networking`:
  - `data_source_networking_floatingip.go`
  - `data_source_networking_floatingip_test.go`
  - `data_source_networking_network.go`
  - `data_source_networking_network_test.go`
  - `data_source_networking_port.go`
  - `data_source_networking_port_test.go`
  - `data_source_networking_router.go`
  - `data_source_networking_router_test.go`
  - `data_source_networking_secgroup.go`
  - `data_source_networking_secgroup_test.go`
  - `data_source_networking_subnet.go`
  - `data_source_networking_subnet_test.go`
  - `networking_floatingip.go`
  - `networking_network.go`
  - `networking_port.go`
  - `networking_port_test.go`
  - `networking_router.go`
  - `networking_router_interface.go`
  - `networking_router_route.go`
  - `networking_router_route_test.go`
  - `networking_secgroup.go`
  - `networking_secgroup_rule.go`
  - `networking_secgroup_rule_test.go`
  - `networking_shared.go`
  - `networking_subnet.go`
  - `networking_subnet_route.go`
  - `networking_subnet_route_test.go`
  - `networking_subnet_test.go`
  - `resource_networking_floatingip.go`
  - `resource_networking_floatingip_associate.go`
  - `resource_networking_floatingip_associate_test.go`
  - `resource_networking_floatingip_test.go`
  - `resource_networking_network.go`
  - `resource_networking_network_test.go`
  - `resource_networking_port.go`
  - `resource_networking_port_secgroup_associate.go`
  - `resource_networking_port_secgroup_associate_test.go`
  - `resource_networking_port_test.go`
  - `resource_networking_router.go`
  - `resource_networking_router_interface.go`
  - `resource_networking_router_interface_test.go`
  - `resource_networking_router_route.go`
  - `resource_networking_router_route_test.go`
  - `resource_networking_router_test.go`
  - `resource_networking_secgroup.go`
  - `resource_networking_secgroup_rule.go`
  - `resource_networking_secgroup_rule_test.go`
  - `resource_networking_secgroup_test.go`
  - `resource_networking_subnet.go`
  - `resource_networking_subnet_route.go`
  - `resource_networking_subnet_route_test.go`
  - `resource_networking_subnet_test.go`
- `publicdns`:
  - `data_source_publicdns_zone.go`
  - `data_source_publicdns_zone_test.go`
  - `publicdns_record.go`
  - `publicdns_zone.go`
  - `resource_publicdns_record.go`
  - `resource_publicdns_record_test.go`
  - `resource_publicdns_zone.go`
  - `resource_publicdns_zone_test.go`
- `region`:
  - `data_source_region.go`
  - `data_source_region_test.go`
  - `data_source_regions.go`
  - `data_source_regions_test.go`
- `sharedfilesystem`:
  - `data_source_sharedfilesystem_share.go`
  - `data_source_sharedfilesystem_share_test.go`
  - `data_source_sharedfilesystem_sharenetwork.go`
  - `data_source_sharedfilesystem_sharenetwork_test.go`
  - `resource_sharedfilesystem_securityservice.go`
  - `resource_sharedfilesystem_securityservice_test.go`
  - `resource_sharedfilesystem_share.go`
  - `resource_sharedfilesystem_share_access.go`
  - `resource_sharedfilesystem_share_access_test.go`
  - `resource_sharedfilesystem_share_test.go`
  - `resource_sharedfilesystem_sharenetwork.go`
  - `resource_sharedfilesystem_sharenetwork_test.go`
  - `sharedfilesystem_share_access.go`
  - `sharedfilesystem_shared.go`
- `vpnaas`:
  - `resource_vpnaas_endpoint_group.go`
  - `resource_vpnaas_endpoint_group_test.go`
  - `resource_vpnaas_ike_policy.go`
  - `resource_vpnaas_ike_policy_test.go`
  - `resource_vpnaas_ipsec_policy.go`
  - `resource_vpnaas_ipsec_policy_test.go`
  - `resource_vpnaas_service.go`
  - `resource_vpnaas_service_test.go`
  - `resource_vpnaas_site_connection.go`
  - `resource_vpnaas_site_connection_test.go`

Also, in order to simplify provider.go, where all data_sources and resources are listed, we could add files `data_sources.go` and `resources.go` to each of services folders. This сan be even done by code generation.

Interesting example of service related settings: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/databricks/registration.go.

CMPT-31302

**Comment by ftersin** [comment]
Could we remove serive name from file names in subfolers?

**Comment by ftersin** [comment]
lb files should not be in db folder

**Comment by paaanic** [comment]
> lb files should not be in db folder

Sure, don't know how it got there.

**Comment by paaanic** [comment]
> Could we remove serive name from file names in subfolers?

Yes. But this approach also has advantages: the file name corresponds to name of resource/datasource, and I  believe this structure should be consistent with the upcoming documentation, grouped by service, where these names should remain full.

**Comment by ftersin** [comment]
hmm... This also has another one - an ability to organize code similar to doc structure, if the last one does not follow service names

**Comment by ftersin** [comment]
done
