### ISSUE TITLE
Невозможно создать мастера/ноды k8s с произвольным размером диска

### ISSUE THREAD

**Issue by kluevandrew** [vk-cs/terraform-provider-vkcs#18]
Может я конечно чего не понимаю, но сейчас шаблон виртуалки для мастера или ноды можно выбрать только указав master_flavor/flavor_id соответсвенно.

`vkcs_compute_flavor` это datasoure, по нему я могу сделать только поиск, в моём случае получилось так

```terraform
data "vkcs_compute_flavor" "master" {
#  name = "Standard-2-4-40"
  vcpus = 2
  ram = 4096
  disk = 40
}

data "vkcs_compute_flavor" "node" {
#  name = "Standard-2-2"
  vcpus = 2
  ram = 2048
}
```

И тут две проблемы, во первых даже с "Standard-2-4-40" создаётся диск на 50 гигов + 10 для etcd, а во вторых для Standard-2-2 тоже создаётся диск на 50 гигов и других вариантов у меня нет. В тоже время в UI я могу создать группу нод с конфигом 2-2-20 и радоваться тому что сэкономил место 

Да и в целом почему у пользователя нет возможности указать произвольный размер диска?

**Comment by joker946** [comment]
Привет! Для указания размера диска в мастере необходимо в ресурсе типа vkcs_kubernetes_cluster указать labels = {"master_volume_size": 20}

В нодгруппах vkcs_kubernetes_node_group есть параметр volume_size

**Comment by kluevandrew** [comment]
Проверил, через labels работает
```terraform
  labels = {
    docker_registry_enabled = false
    prometheus_monitoring = false
    cluster_node_volume_type = "high-iops"
    etcd_volume_size = 10
    master_volume_size = 20
  }
  ```
  
Предлагаю как минимум описать в документации, а для следующих ресурсов вынести в свойства ресурса для повышения usability

- cluster_node_volume_type
- etcd_volume_size 
- master_volume_size
