### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by der-andrew** [vk-cs/terraform-provider-vkcs#407]
In some data-sources there are resources infact.
Here are:
https://github.com/vk-cs/terraform-provider-vkcs/blob/master/docs/data-sources/networking_port.md
https://github.com/vk-cs/terraform-provider-vkcs/blob/master/docs/data-sources/networking_floatingip.md
https://github.com/vk-cs/terraform-provider-vkcs/blob/master/docs/data-sources/networking_router.md
so on...

**Comment by ftersin** [comment]
thanks

**Comment by paaanic** [comment]
Fixed in #413
