### ISSUE TITLE
Impossible to associate fip to loadbalancer port

### ISSUE THREAD

**Issue by cognoz** [vk-cs/terraform-provider-vkcs#478]
## Used versions
Provider version - v0.8.1  
Terraform version - v1.9.4

## Use case
I want to be able to create a loadbalancer with external port (i.e. fip). 

## The issue
It seems (though I'm not sure) that in older versions of the provider it was possible via referencing to port_id in   vkcs_compute_floatingip_associate resource. But now it takes only instance_id as a reference (and supplying loadbalancer id as an argument obviously ends up with code 404, infra...:8774/v.2.1/servers/loadbalancer-id/action not found).  

Is there any workarounds besides using cli/UI to assign fip to Loadbalancer?

**Comment by paaanic** [comment]
Hi, you can use `vkcs_networking_floating_ip_associate` (https://github.com/vk-cs/terraform-provider-vkcs/blob/master/docs/resources/networking_floatingip_associate.md) resource to associate an existing floating with a loadbalancer port, or you can create a new one specifying `port_id` in `vkcs_networking_floating_ip`.
