### ISSUE TITLE
How to create private network via vkcs_networking_network?

### ISSUE THREAD

**Issue by kvendingoldo** [vk-cs/terraform-provider-vkcs#49]
Hi,
I can find any `external` attributes for `vkcs_networking_network`. Is it possible to create private network anyhow? (maybe via `value_specs` map?)

**Comment by kvendingoldo** [comment]
Hi folks (@schirevko @ftersin ). Do you maybe know?

**Comment by ftersin** [comment]
@kvendingoldo You do not have to specify any kind of `external` attribute to create private network. See example https://github.com/vk-cs/terraform-provider-vkcs/blob/746ebb29256360aa448ba2116c31bf978b521b5e/examples/vkcs-networking-common/main.tf

**Comment by kvendingoldo** [comment]
@ftersin but how to restrict the Internet access? I do not see any flags in documentation
https://registry.terraform.io/providers/vk-cs/vkcs/latest/docs/resources/vkcs_networking_network

Now I create smth for that:
```
resource "vkcs_networking_network" "main" {
  name = "test"
  admin_state_up       = true
  vkcs_services_access = true
}
```
and getting the following state in VK admin panel: 
<img width="603" alt="Screenshot 2022-08-10 at 13 43 50" src="https://user-images.githubusercontent.com/11614750/183870649-b4971f69-7ae6-4000-b5b6-b0c430d635f4.png">

**Comment by ftersin** [comment]
> how to restrict the Internet access

Internet access is controlled by router with external_network_id argument.
