### ISSUE TITLE
vkcs_lb_listener - default_pool_id should be Required parameter

### ISSUE THREAD

**Issue by Nmishin** [vk-cs/terraform-provider-vkcs#80]
For now default_pool_id marked as "Optional". But without default_pool_id listener isn't work correctly.

**Comment by Etoneja** [comment]
Need clarification on what exactly is not working correctly.

Load balancer service principles:

- The pool can be created as a default listener pool or as a balancer pool
- The pool can be associated to the listener through the default pool or through the l7 policy (redirect to pool)
- Default pool - is the pool that used by the listener if no L7 policies match
- Listener may have no or only one default pool

So, **default_pool_id** is really an optional field for the listener and we should not restrict it in any way in provider.
