### ISSUE TITLE
DBaaS output local IP/floating IP

### ISSUE THREAD

**Issue by hmelnoff** [vk-cs/terraform-provider-vkcs#81]
Привет. Создаю инстанс DBaaS, подскажите как в output вывести его локальный или внешний IP адрес, есть ли такая возможность?

**Comment by schirevko** [comment]
Привет, можно описать датасорс для этого инстанса и смотреть поле ip этого датасорса:

data "vkcs_db_instance" "tf-instance" {
    id = vkcs_db_instance.tf-instance.id
}

output "instance_ip_addr" {
    value = data.vkcs_db_instance.tf-instance.ip
}
